{% set name = "cuda-core" %}
{% set version = "0.5.0" %}
{% set number = 0 %}
{% set is_freethreading = environ.get("is_freethreading", False) %}

{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win64]
{% set subdir = "" %}
{% set subdir = os.sep.join(["", "targets", target_name]) %}  # [linux64 or aarch64]
{% set subdir = os.sep.join(["", "Library"]) %}               # [win64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/releases/download/{{ name }}-v{{ version }}/cuda-python-{{ name }}-v{{ version }}.tar.gz
  sha256: c2b68fe7c5557a33d275f4516d781738566f90f9b6caab43844401033e21b670

build:
  number: {{ number }}
  string: cuda{{ cuda_major_version }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  skip: true  # [py < 310 or ppc64le or osx]
  script_env:
    - CUDA_PATH={{ PREFIX ~ subdir }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
  host:
    - cython
    - pip
    - python
    - setuptools
    - cuda-cudart-dev
    - cuda-profiler-api
    - cuda-bindings {{ cuda_major_version }}.*
    - cuda-version {{ cuda_major_version }}.*
  run:
    - python
    - numpy
    - {{ pin_compatible("cuda-bindings", min_pin="x", max_pin="x") }}
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}

test:
  commands:
    - python -c "from cuda.core.experimental import Device, Buffer, utils; print('ok')"

about:
  home: https://nvidia.github.io/cuda-python/cuda-core
  license: Apache-2.0
  license_file: cuda_core/LICENSE
  license_url: https://github.com/NVIDIA/cuda-python/blob/main/cuda_core/LICENSE
  summary: "cuda.core: (experimental) pythonic CUDA module"
  description: |
    cuda.core bridges Python's productivity with CUDA's performance through intuitive and pythonic APIs.
    The mission is to provide users full access to all of the core CUDA features in Python, such as
    runtime control, compiler and linker.
  doc_url: https://nvidia.github.io/cuda-python/cuda-core
  dev_url: https://github.com/NVIDIA/cuda-python

extra:
  recipe-maintainers:
    - conda-forge/cuda-python
    - bdice
    - leofang
    - kkraus14
